INSERT INTO questions (que_id, question_type, que_content, que_point, ans_content, c_id) VALUES
-- 10 أسئلة C# (id المادة: 204)
(1, 'True/False', 'C# is case-sensitive.', 1, 'True', 204),
(2, 'MCQ', 'Which keyword is used to define a constant in C#?', 3, 'const', 204),
(3, 'True/False', 'Interfaces in C# can contain fields.', 1, 'False', 204),
(4, 'MCQ', 'Which class is used for file operations in C#?', 3, 'File', 204),
(5, 'MCQ', 'What is the default access modifier for a class in C#?', 3, 'internal', 204),
(6, 'True/False', 'C# supports multiple inheritance.', 1, 'False', 204),
(7, 'MCQ', 'Which keyword is used to implement an interface?', 3, ':', 204),
(8, 'True/False', 'Abstract classes can have constructors in C#.', 1, 'True', 204),
(9, 'MCQ', 'Which method is used to start a thread in C#?', 3, 'Start', 204),
(10, 'MCQ', 'What is the base class of all classes in C#?', 3, 'Object', 204),

-- 10 أسئلة OOP (id المادة: 202)
(11, 'True/False', 'Polymorphism allows method overriding.', 1, 'True', 202),
(12, 'MCQ', 'Which OOP principle refers to hiding details?', 3, 'Encapsulation', 202),
(13, 'True/False', 'A constructor has a return type.', 1, 'False', 202),
(14, 'MCQ', 'Which keyword is used to inherit a class?', 3, ':', 202),
(15, 'MCQ', 'Which OOP principle allows reusability?', 3, 'Inheritance', 202),
(16, 'True/False', 'Encapsulation means exposing all class variables.', 1, 'False', 202),
(17, 'MCQ', 'Which keyword is used to create an object in Java?', 3, 'new', 202),
(18, 'True/False', 'Abstract classes can be instantiated.', 1, 'False', 202),
(19, 'MCQ', 'Which OOP principle is related to overriding?', 3, 'Polymorphism', 202),
(20, 'MCQ', 'Which keyword is used for method overriding?', 3, 'override', 202),

-- 10 أسئلة SQL (id المادة: 203)
(21, 'True/False', 'SQL stands for Structured Query Language.', 1, 'True', 203),
(22, 'MCQ', 'Which SQL clause is used to filter records?', 3, 'WHERE', 203),
(23, 'True/False', 'The PRIMARY KEY allows duplicate values.', 1, 'False', 203),
(24, 'MCQ', 'Which command is used to delete a table?', 3, 'DROP TABLE', 203),
(25, 'MCQ', 'Which function returns the total count of rows?', 3, 'COUNT', 203),
(26, 'True/False', 'SQL is case-sensitive.', 1, 'False', 203),
(27, 'MCQ', 'Which command is used to update a record?', 3, 'UPDATE', 203),
(28, 'True/False', 'JOIN is used to combine rows from multiple tables.', 1, 'True', 203),
(29, 'MCQ', 'Which SQL keyword retrieves unique values?', 3, 'DISTINCT', 203),
(30, 'MCQ', 'Which SQL statement is used to remove duplicates?', 3, 'GROUP BY', 203),

-- 10 أسئلة HTML (id المادة: 201)
(31, 'True/False', 'HTML stands for Hyper Text Markup Language.', 1, 'True', 201),
(32, 'MCQ', 'Which tag is used to create a hyperlink?', 3, '<a>', 201),
(33, 'True/False', 'The <br> tag is used for a horizontal line.', 1, 'False', 201),
(34, 'MCQ', 'Which tag is used to define a table row?', 3, '<tr>', 201),
(35, 'MCQ', 'What does the <title> tag define?', 3, 'Webpage title', 201),
(36, 'True/False', 'HTML is a programming language.', 1, 'False', 201),
(37, 'MCQ', 'Which tag is used for images in HTML?', 3, '<img>', 201),
(38, 'True/False', 'The <p> tag is used for paragraphs.', 1, 'True', 201),
(39, 'MCQ', 'Which attribute specifies an image path?', 3, 'src', 201),
(40, 'MCQ', 'Which tag is used for bold text?', 3, '<b>', 201),

-- 10 أسئلة C (id المادة: 205)
(41, 'True/False', 'C is a procedural programming language.', 1, 'True', 205),
(42, 'MCQ', 'Which data type is used to store a single character?', 3, 'char', 205),
(43, 'True/False', 'C supports function overloading.', 1, 'False', 205),
(44, 'MCQ', 'Which operator is used to allocate memory dynamically?', 3, 'malloc', 205),
(45, 'MCQ', 'Which function is used to print output in C?', 3, 'printf', 205),
(46, 'True/False', 'C supports OOP principles.', 1, 'False', 205),
(47, 'MCQ', 'Which function is used to take input in C?', 3, 'scanf', 205),
(48, 'True/False', 'The main function in C can return void.', 1, 'True', 205),
(49, 'MCQ', 'Which loop is used when the number of iterations is fixed?', 3, 'for', 205),
(50, 'MCQ', 'Which symbol is used for comments in C?', 3, '//', 205),

-- 10 أسئلة C# (تابع) (id المادة: 204)
(51, 'True/False', 'C# supports automatic garbage collection.', 1, 'True', 204),
(52, 'MCQ', 'Which of the following is NOT a valid C# data type?', 3, 'integer', 204),
(53, 'True/False', 'C# allows multiple class inheritance.', 1, 'False', 204),
(54, 'MCQ', 'Which operator is used to access members of a namespace?', 3, '.', 204),
(55, 'MCQ', 'Which keyword is used to define a method in C#?', 3, 'void', 204),
(56, 'True/False', 'Static methods belong to an instance of a class.', 1, 'False', 204),
(57, 'MCQ', 'Which keyword is used to create an abstract class?', 3, 'abstract', 204),
(58, 'True/False', 'C# provides both value types and reference types.', 1, 'True', 204),
(59, 'MCQ', 'What is the correct way to declare a nullable integer?', 3, 'int? x;', 204),
(60, 'MCQ', 'Which collection type allows duplicate keys in C#?', 3, 'Hashtable', 204),

-- 10 أسئلة OOP (تابع) (id المادة: 202)
(61, 'True/False', 'All classes in Java inherit from Object.', 1, 'True', 202),
(62, 'MCQ', 'Which OOP concept refers to code reusability?', 3, 'Inheritance', 202),
(63, 'True/False', 'A private method can be accessed outside its class.', 1, 'False', 202),
(64, 'MCQ', 'Which keyword is used for dynamic method dispatch?', 3, 'virtual', 202),
(65, 'MCQ', 'Which feature of OOP provides multiple implementations?', 3, 'Polymorphism', 202),
(66, 'True/False', 'Abstract methods must have a body.', 1, 'False', 202),
(67, 'MCQ', 'Which access modifier allows access within the same package?', 3, 'default', 202),
(68, 'True/False', 'Encapsulation means bundling data and methods together.', 1, 'True', 202),
(69, 'MCQ', 'Which keyword is used to create an interface?', 3, 'interface', 202),
(70, 'MCQ', 'Which OOP principle promotes data hiding?', 3, 'Encapsulation', 202),

-- 10 أسئلة SQL (تابع) (id المادة: 203)
(71, 'True/False', 'The UNIQUE constraint allows duplicate values.', 1, 'False', 203),
(72, 'MCQ', 'Which SQL command is used to add a new column?', 3, 'ALTER TABLE', 203),
(73, 'True/False', 'HAVING clause is used with aggregate functions.', 1, 'True', 203),
(74, 'MCQ', 'Which SQL statement is used to remove all rows from a table?', 3, 'TRUNCATE', 203),
(75, 'MCQ', 'Which function returns the highest value in a column?', 3, 'MAX', 203),
(76, 'True/False', 'GROUP BY is used to group rows with similar values.', 1, 'True', 203),
(77, 'MCQ', 'Which SQL clause sorts the result set?', 3, 'ORDER BY', 203),
(78, 'True/False', 'SQL injection is a security threat.', 1, 'True', 203),
(79, 'MCQ', 'Which SQL constraint ensures a column cannot have NULL values?', 3, 'NOT NULL', 203),
(80, 'MCQ', 'Which command is used to remove a database?', 3, 'DROP DATABASE', 203),

-- 10 أسئلة HTML (تابع) (id المادة: 201)
(81, 'True/False', 'HTML5 introduced the <canvas> element.', 1, 'True', 201),
(82, 'MCQ', 'Which tag is used to define a form in HTML?', 3, '<form>', 201),
(83, 'True/False', 'The <ul> tag is used for numbered lists.', 1, 'False', 201),
(84, 'MCQ', 'Which tag is used for creating a dropdown list?', 3, '<select>', 201),
(85, 'MCQ', 'Which attribute is used to specify an image width?', 3, 'width', 201),
(86, 'True/False', 'HTML comments are written inside <!-- -->.', 1, 'True', 201),
(87, 'MCQ', 'Which element is used for embedding videos?', 3, '<video>', 201),
(88, 'True/False', 'HTML is case-sensitive.', 1, 'False', 201),
(89, 'MCQ', 'Which tag is used for making text italic?', 3, '<i>', 201),
(90, 'MCQ', 'Which HTML attribute specifies an alternative text for an image?', 3, 'alt', 201),

-- 10 أسئلة C (تابع) (id المادة: 205)
(91, 'True/False', 'The sizeof operator returns the size of a variable.', 1, 'True', 205),
(92, 'MCQ', 'Which header file is used for input/output functions?', 3, 'stdio.h', 205),
(93, 'True/False', 'A struct can contain functions in C.', 1, 'False', 205),
(94, 'MCQ', 'Which keyword is used to exit from a loop?', 3, 'break', 205),
(95, 'MCQ', 'Which function is used to copy strings?', 3, 'strcpy', 205),
(96, 'True/False', 'C uses pass-by-value by default.', 1, 'True', 205),
(97, 'MCQ', 'Which loop is best when the number of iterations is unknown?', 3, 'while', 205),
(98, 'True/False', 'Pointers store the memory address of a variable.', 1, 'True', 205),
(99, 'MCQ', 'Which function is used to find the length of a string?', 3, 'strlen', 205),
(100, 'MCQ', 'Which operator is used for bitwise AND?', 3, '&', 205),

-- 10 أسئلة C# (تابع) (id المادة: 204)
(101, 'True/False', 'C# supports method overloading.', 1, 'True', 204),
(102, 'MCQ', 'Which keyword is used to handle exceptions in C#?', 3, 'try', 204),
(103, 'True/False', 'C# arrays can dynamically resize themselves.', 1, 'False', 204),
(104, 'MCQ', 'Which of the following is NOT an access modifier in C#?', 3, 'protected-internal', 204),
(105, 'MCQ', 'Which collection class allows unique keys?', 3, 'Dictionary', 204),
(106, 'True/False', 'Structs in C# are reference types.', 1, 'False', 204),
(107, 'MCQ', 'What is the default value of a boolean variable in C#?', 3, 'False', 204),
(108, 'True/False', 'Interfaces in C# cannot have fields.', 1, 'True', 204),
(109, 'MCQ', 'Which keyword is used to inherit a class?', 3, ':', 204),
(110, 'MCQ', 'What is the base class of all .NET classes?', 3, 'Object', 204),

-- 10 أسئلة OOP (تابع) (id المادة: 202)
(111, 'True/False', 'A class can implement multiple interfaces.', 1, 'True', 202),
(112, 'MCQ', 'Which OOP concept helps reduce code duplication?', 3, 'Inheritance', 202),
(113, 'True/False', 'A constructor can be private.', 1, 'True', 202),
(114, 'MCQ', 'Which of these is NOT a fundamental OOP concept?', 3, 'Compilation', 202),
(115, 'MCQ', 'Which function is called automatically when an object is created?', 3, 'Constructor', 202),
(116, 'True/False', 'Static methods can be overridden.', 1, 'False', 202),
(117, 'MCQ', 'Which of the following restricts object creation?', 3, 'Private constructor', 202),
(118, 'True/False', 'A subclass can override a static method.', 1, 'False', 202),
(119, 'MCQ', 'Which keyword is used to prevent inheritance?', 3, 'sealed', 202),
(120, 'MCQ', 'Which function runs when an object is destroyed?', 3, 'Destructor', 202),

-- 10 أسئلة SQL (تابع) (id المادة: 203)
(121, 'True/False', 'SQL views can store data permanently.', 1, 'False', 203),
(122, 'MCQ', 'Which SQL clause removes duplicate records?', 3, 'DISTINCT', 203),
(123, 'True/False', 'A primary key can have NULL values.', 1, 'False', 203),
(124, 'MCQ', 'Which SQL statement is used to update records?', 3, 'UPDATE', 203),
(125, 'MCQ', 'Which keyword is used to define a unique value constraint?', 3, 'UNIQUE', 203),
(126, 'True/False', 'INNER JOIN returns only matching records.', 1, 'True', 203),
(127, 'MCQ', 'Which SQL clause filters aggregated data?', 3, 'HAVING', 203),
(128, 'True/False', 'The COUNT function ignores NULL values.', 1, 'True', 203),
(129, 'MCQ', 'Which SQL statement deletes records from a table?', 3, 'DELETE', 203),
(130, 'MCQ', 'Which function is used to get the current date?', 3, 'CURDATE', 203),

-- 10 أسئلة HTML (تابع) (id المادة: 201)
(131, 'True/False', 'The <footer> tag is used to define the header of a page.', 1, 'False', 201),
(132, 'MCQ', 'Which tag is used to display a table?', 3, '<table>', 201),
(133, 'True/False', 'HTML supports case-sensitive tags.', 1, 'False', 201),
(134, 'MCQ', 'Which attribute specifies the URL of a hyperlink?', 3, 'href', 201),
(135, 'MCQ', 'Which tag is used for adding JavaScript code?', 3, '<script>', 201),
(136, 'True/False', 'The <strong> tag makes text italic.', 1, 'False', 201),
(137, 'MCQ', 'Which HTML element is used for defining a division?', 3, '<div>', 201),
(138, 'True/False', 'HTML5 introduced the <article> tag.', 1, 'True', 201),
(139, 'MCQ', 'Which tag is used to create a checkbox?', 3, '<input type="checkbox">', 201),
(140, 'MCQ', 'Which HTML attribute specifies an image path?', 3, 'src', 201),

-- 10 أسئلة C (تابع)
(141, 'True/False', 'C allows function overloading.', 1, 'False', 205),
(142, 'MCQ', 'Which function is used to read input in C?', 3, 'scanf', 205),
(143, 'True/False', 'Pointers in C cannot be NULL.', 1, 'False', 205),
(144, 'MCQ', 'Which operator is used for pointer dereferencing?', 3, '*', 205),
(145, 'MCQ', 'Which function allocates memory dynamically?', 3, 'malloc', 205),
(146, 'True/False', 'The do-while loop executes at least once.', 1, 'True', 205),
(147, 'MCQ', 'Which loop executes a fixed number of times?', 3, 'for', 205),
(148, 'True/False', 'The switch statement can be replaced with if-else.', 1, 'True', 205),
(149, 'MCQ', 'Which function is used to compare two strings?', 3, 'strcmp', 205),
(150, 'MCQ', 'Which header file contains mathematical functions?', 3, 'math.h', 205);